#!/bin/bash

# exit with metadata.xml to report job status to opal2
function niceexit {
        rcode=$1
        input="$2"
        output="$3"
        msg="$4"
        rfile=$WORK_DIR/metadata.xml
        echo "$msg"
        if [ $rcode -eq 0 ]; then
                echo -e "<results><status>success</status><input>$input</input><output>$output</output><message/></results>" >$rfile
                exit 0
        else
                echo -e "<results><status>failed</status><input>$input</input><output/><message>$msg</message></results>" >$rfile
                exit $rcode
        fi
}

set -e

# setting a WORK_DIR singlas to run-master that it does not need to set up
# a new one
export WORK_DIR=`readlink -f .`

# figure out what the base dir of this script is
SOL_INSTALL_DIR=`dirname $0`
SOL_INSTALL_DIR=`cd $SOL_INSTALL_DIR && pwd`

# safty check
if [ -e run-master ]; then
    niceexit 1 "" "" "Error: Do not run from the Sol checkout!"
fi

echo "[`date`] setting up for the workflow..."
t0=`date +%s`
# arguments
DEMURL=$1
zipfile="output.zip"
if [ ! -z "$2" ]; then
        oname="`basename $2`"
        [ "`basename $oname .zip`" == "${oname}" ] && oname="${oname}.zip"
        zipfile="$oname"
fi

tdir=/tmp/eemt_tmp.$RANDOM
mkdir -p $tdir
cd $tdir
DEMTAR=`basename $DEMURL`
wget -nv $DEMURL 2>&1
[ $? -ne 0 ] && niceexit 1 $DEMURL $zipfile "Error: could not download DEM $DEMURL."
echo "[`date`] downloaded DEM from $DEMURL"

cd $WORK_DIR/
tar xfz $tdir/$DEMTAR
[ $? -ne 0 ] && niceexit 1 $DEMURL $zipfile "Error: could not unzip DEM from $DEMURL."
DEM=$(basename `ls *.tif | head -n 1`) 
rm -fr $tdir/$DEMTAR

# let's make sure the dem has a sane name
DEM_NAME_FIXED=`echo "$DEM" | sed 's/\.tif$//' | sed 's/\./_/g'`".tif"
if [ "$DEM" != "$DEM_NAME_FIXED" ]; then
    echo "[`date`] Fixed the DEM file nameing: $DEM -> $DEM_NAME_FIXED"
    mv $DEM $DEM_NAME_FIXED
    DEM=$DEM_NAME_FIXED
fi

cd $SOL_INSTALL_DIR

t1=`date +%s`
# run the workflow
echo "[`date`] starting the workflow..."
echo
echo "================================================================="
echo
./run-master $WORK_DIR/$DEM 2>&1
retcode=$?
t2=`date +%s`
if [ $retcode -eq 0 ]; then
        echo "[`date`] archiving output ..."
        cd $WORK_DIR && zip -r $zipfile global/monthly insol/monthly
fi
echo
echo "[`date`] Finished, workflow returned exit code $retcode. Output files in $WORK_DIR . Output archive in $WORK_DIR/$zipfile ."
echo "Time in sec: download `expr $t1 \- $t0` ; workflow `expr $t2 \- $t1`"
niceexit $retcode $DEMURL $zipfile "Input from $DEMURL. Output in $WORK_DIR/$zipfile . Execution time: `expr $t2 \- $t0` seconds"


