#!/bin/bash

set -e

function find_work_dir()
{
    echo "Finding a working directory with enough disk space..."
    targets="$_CONDOR_SCRATCH_DIR $SCRATCH $TMPDIR $TMP /tmp $PWD"
    for d in $targets; do
        # does the target exist?
        if [ ! -e $d ]; then
            echo " ... $d does not exist"
            continue
        fi
        # make sure there is enough available diskspace
        cd $d
        free=`df -kP . | awk '{if (NR==2) print $4}'`
        free_human=`df --si . | awk '{if (NR==2) print $4}'`
        if [ "x$free" == "x" -o $free -lt 1000000 ]; then
            echo " ... not enough disk space available in $d"
            continue
        fi
        if touch $d/.dirtest.$$ >/dev/null 2>&1; then
            rm -f $d/.dirtest.$$ >/dev/null 2>&1
            d=`mktemp -d $d/worker.XXXXXXXXX`
            export WORK_DIR="$d"
            echo "Using $d as work directory!"
            return 0
        fi
        echo " ... not allowed to write to $d"
    done
    return 1
}


# figure out the full path for the top directory
TOP_DIR=`dirname $0`
TOP_DIR=`cd $TOP_DIR && pwd`

# make sure we have a password, and create a hash for the project name
if [ ! -r ~/.eemt-makeflow-password ]; then
    echo "Please create ~/.eemt-makeflow-password , and populate it with your workqueue password"
    exit 1
fi
PW_HASH=`cat ~/.eemt-makeflow-password | sha256sum | cut -d ' ' -f 1`

# env
export TCP_LOW_PORT=20000
export TCP_HIGH_PORT=60000 
module load singularity >/dev/null 2>&1 || true

# should be in the container
export PYTHONPATH=/opt/eemt/lib/python2.6/site-packages:/opt/eemt/lib64/python2.6/site-packages

# download the container if we do not already have it
if [ ! -e "$TOP_DIR/eemt-current.img" ]; then
    wget -nv -O $TOP_DIR/eemt-current.img \
         http://xd-login.opensciencegrid.org/scratch/eemt/singularity/eemt-current.img
fi

# we need a temporary directory to run from
if ! find_work_dir; then
    echo "Unable to find a work dir with enough space! Exiting..."
    exit 1
fi
cd $WORK_DIR
cp $TOP_DIR/sol/* ./

# we also need the password file
cp ~/.eemt-makeflow-password ./

# run the workflow
singularity exec \
  --home $PWD:/srv \
  --pwd /srv \
  --scratch /var/tmp \
  --scratch /tmp \
  --contain --ipc --pid \
  $TOP_DIR/eemt-current.img \
  work_queue_worker -P .eemt-makeflow-password \
                    -M EEMT-$PW_HASH \
                    -s /srv \
                    -t 600 \
                    --cores=0

