#!/bin/bash

set -e

# figure out the full path for the top directory
TOP_DIR=`dirname $0`
TOP_DIR=`cd $TOP_DIR && pwd`

# similarly, full path to DEM
if [ "x$1" = "x" ]; then
    echo "Error: Please specify the DEM to run as the only argument"
    exit 1
fi
DEM_DIR=`dirname $1`
DEM_DIR=`cd $DEM_DIR && pwd`
DEM_NAME=`basename $1`
DEM="$DEM_DIR/$DEM_NAME"

STEP=$2
LINKE_VALUE=$3
ALBEDO_VALUE=$4

# default values
if [ "x$STEP" = "x" ]; then
    STEP="0.5"
fi
if [ "x$LINKE_VALUE" = "x" ]; then
    LINKE_VALUE="3.0"
fi
if [ "x$ALBEDO_VALUE" = "x" ]; then
    ALBEDO_VALUE="0.2"
fi

# make sure we have a password, and create a hash for the project name
if [ ! -r ~/.eemt-makeflow-password ]; then
    echo "Please create ~/.eemt-makeflow-password , and populate it with your workqueue password"
    exit 1
fi
PW_HASH=`cat ~/.eemt-makeflow-password | sha256sum | cut -d ' ' -f 1`

# env
export TCP_LOW_PORT=20000
export TCP_HIGH_PORT=60000 
module load singularity >/dev/null 2>&1 || true

# should be in the container
export PYTHONPATH=/opt/eemt/lib/python2.7/site-packages

# we need a temporary directory to run from
if [ "x$WORK_DIR" = "x" ]; then
    WORK_DIR=`mktemp -d -t master.XXXXXXXX`
fi
cd $WORK_DIR
cp $TOP_DIR/sol/* ./
if [ ! -e $DEM_NAME ]; then
    cp $DEM ./
fi

# download the container if we do not already have it
if [ ! -e "$WORK_DIR/eemt-current.img" ]; then
    wget -nv -O $WORK_DIR/eemt-current.img \
         http://xd-login.opensciencegrid.org/scratch/eemt/singularity/eemt-current.img
fi

# we also need the password file
cp ~/.eemt-makeflow-password ./

# run the workflow
singularity exec \
  --home $PWD:/srv \
  --pwd /srv \
  --scratch /var/tmp \
  --scratch /tmp \
  --contain --ipc --pid \
  $WORK_DIR/eemt-current.img \
  /srv/run-workflow \
    --name EEMT-$PW_HASH \
    --step $STEP \
    --linke_value $LINKE_VALUE \
    --albedo_value $ALBEDO_VALUE \
    -O /srv/work \
    /srv/$DEM_NAME

echo
echo "Output files in $WORK_DIR/work"
echo

