#!/bin/bash

# this is just a wrapper around run-master which sets up the workdir expected by
# opal2

set -e

# WORK_DIR is also used by run-master
export WORK_DIR=`pwd`

# figure out the full path for the sol directory
SOL_INSTALL=`dirname $0`
SOL_INSTALL=`cd $LOCAL_SOL_INSTALL && pwd`

# safety check
if [ -e run-master -o -e run-workflow ]; then
    echo "Do not run from the Sol checkout!"
    exit 1
fi

# arguments
DEM=$1

# tell run-master where to do the work

set +e
$SOL_INSTALL/run-master $DEM
EXIT_CODE=$?
set -e

# clean up
rm -f eemt-current.img
rm -f .eemt-makeflow-password

exit $EXIT_CODE

