name: harbor

on:
  push:
    branches: 2022

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: harbor.cyverse.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      
      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v3.1.1
        with:
          context: latest 
          file: docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: harbor.cyverse.org/vice/jupyter/eemt:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
